# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28401f177f8a128489b0a63bc53cb40cfaff5b7fc57d56055b43e29394dc2c3bec7ec1885e30fda07d7c57090f3ea3dd70970993d3ac3ac113792304679194c7

test:
  secret_key_base: 2cf75e7fc7ccf79ea22fe1522b80a0f835cf3468540f16217112bb77c013e8eb8653dae7fe6663bffaf05323d7b092ebd27cba43eba5b7b2a6c17bc1ff7d0937

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
